apps/manpower/urls.py
from django.urls import path
from apps.manpower.views import AsistenciaDelete, AsistenciaUpdate, DescargueCreate, DescargueDelete, DescargueUpdate, HomeView, PersonalCreate, PersonalDelete, PersonalList, PersonalUpdate, PreliminarCreate, PreliminarDelete, PreliminarDetail, PreliminarList, AsistenciaList, AsistenciaCreate, DescargueList, NominaView, PreliminarUpdate
from apps.manpower.report import export_preliminar_excel
from django.contrib.auth.decorators import login_required

app_name = 'nomina'

urlpatterns = [
    path('', login_required(HomeView.as_view()), name='inicio'),
    path('nomina', login_required(NominaView.as_view()), name='nomina_list'),
    # Personal
    path('personalList', login_required(PersonalList.as_view()), name='personal_list'),
    path('personalCreate', login_required(PersonalCreate.as_view()), name='personal_create'),
    path('personalUpdate/<str:pk>/', login_required(PersonalUpdate.as_view()), name='personal_update'),
    path('personalDelete/<str:pk>/', login_required(PersonalDelete.as_view()), name='personal_delete'),
    # Preliminar
    path('preliminarList', login_required(PreliminarList.as_view()), name='preliminar_list'),
    path('preliminarCreate', login_required(PreliminarCreate.as_view()), name='preliminar_create'),
    # Nomina
    path('nomina/<int:pk>/', login_required(PreliminarDetail.as_view()), name='nomina_detail'),
    path('nominaUpdate/<int:pk>/', login_required(PreliminarUpdate.as_view()), name='nomina_update'),
    path('nominaDelete/<int:pk>/', login_required(PreliminarDelete.as_view()), name='nomina_delete'),
    # Asistencia
    path('asistenciaList', login_required(AsistenciaList.as_view()), name='asistencia_list'),
    path('asistenciaCreate', login_required(AsistenciaCreate.as_view()), name='asistencia_create'),
    path('asistenciaUpdate/<int:pk>/', login_required(AsistenciaUpdate.as_view()), name='asistencia_update'),
    path('asistenciaDelete/<int:pk>/', login_required(AsistenciaDelete.as_view()), name='asistencia_delete'),
    # Descargue
    path('descargueList', login_required(DescargueList.as_view()), name='descargue_list'),
    path('descargueCreate', login_required(DescargueCreate.as_view()), name='descargue_create'),
    path('descargueUpdate/<int:pk>/', login_required(DescargueUpdate.as_view()), name='descargue_update'),
    path('descargueDelete/<int:pk>/', login_required(DescargueDelete.as_view()), name='descargue_delete'),
    # Reporte
    path("export-preliminar/<int:pk>", login_required(export_preliminar_excel), name="export_preliminar"),

    
]

seunicsa/urls.py
# urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.auth.decorators import login_required

from seunicsa.views import IndexView

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_then_login, name='logout'),
    path('admin/', admin.site.urls),
    path('home/', login_required(IndexView.as_view()), name='inicio'),
    path('nomina/', include('apps.manpower.urls')),
]

templates/asistencia/asistencia_delete.html
{% extends 'index.html' %}
{% block pageContent %}
    {% if form.errors %}
        <div class="alert alert-danger m-4" role="alert">
          Verifique los valores <strong> - intente de nuevo!</strong>
        </div>
    {% endif %}
    <div class="card shadow-lg border-0 rounded-lg mt-5 mx-4">
        <div class="card-header">
            <strong>Registro De Asistencia</strong>
        </div>
        <div class="card-body">
            <form method="post">{% csrf_token %}
                <p>Está seguro que desea eliminar "{{ object }}" ?</p>
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-trash"></i>
                    Eliminar
                </button>
                <a href="{% url 'nomina:asistencia_list' %}" class="btn btn-secondary">
                    <i class="fas fa-times-circle"></i>
                    Cancelar
                </a>
            </form>
        </div>
    </div>
{% endblock pageContent %}

templates/asistencia/asistencia_form.html
{% extends 'index.html' %}
{% block pageContent %}
    {% if form.errors %}
        <div class="alert alert-danger m-4" role="alert">
          Verifique los valores <strong> - intente de nuevo!</strong>
        </div>
    {% endif %}
    <div class="card shadow-lg border-0 rounded-lg mt-5 mx-4">
        <div class="card-header">
            <strong>Registro De Asistencia</strong>
        </div>
        <div class="card-body">
            <form method="post">{% csrf_token %}
                <div class="row">
                    <div class="col">
                        <label for="#">{{ form.personal.label }}</label>
                        {{ form.personal }}
                    </div>
                    <div class="col">
                        <label for="#">{{ form.cargo.label }}</label>
                        {{ form.cargo }}
                    </div>
                    <div class="col">
                        <label for="#">{{ form.campania.label }}</label>
                        {{ form.campania }}
                    </div>
                    <div class="col">
                        <label for="#">{{ form.fecha.label }}</label>
                        {{ form.fecha }}
                    </div>
                </div>
                <div class=" py-3">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Guardar</button>
                    <a href="{% url 'nomina:asistencia_list' %}" class="btn btn-secondary"><i class="fas fa-trash-alt"></i> Cancelar</a>
                </div>
            </form>
        </div>
    </div>
{% endblock pageContent %}

templates/asistencia/asistencia_list.html
{% extends 'index.html' %}
{% block pageContent %}
    {% if asistencia_list %}
        <h2 class="mt-3">Registro De Asistencia</h2>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{% url 'nomina:inicio' %}">SEUNICSA</a></li>
            <li class="breadcrumb-item active">Asistencia</li>
        </ol>
        <div class="card mb-4">
            <div class="card-body">
                Agregar un nuevo registro al sistema de nomina <strong>SEUNICSA</strong>
                <div class=" py-3">
                    <a href="{% url 'nomina:asistencia_create' %}" class="btn btn-primary"><i
                            class="fas fa-plus-circle"></i> Agregar</a>
                </div>
            </div>
        </div>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Registro De Asistencia
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Campaña</th>
                        <th scope="col">Cargo</th>
                        <th scope="col">Fecha</th>
                        {% if user.is_superuser %}
                            <th scope="col">Acciones</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Campaña</th>
                        <th scope="col">Cargo</th>
                        <th scope="col">Fecha</th>
                        {% if user.is_superuser %}
                            <th scope="col">Acciones</th>
                        {% endif %}
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for asistencia in asistencia_list %}
                        <tr>
                            <td>{{ asistencia.personal }}</td>
                            <td>{{ asistencia.campania }}</td>
                            <td>{{ asistencia.cargo }}</td>
                            <td>{{ asistencia.fecha }}</td>
                            {% if user.is_superuser %}
                                <td>
                                    <a href="{% url 'nomina:asistencia_update' asistencia.id %}"
                                    class="btn btn-success btn-circle btn-sm">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="{% url 'nomina:asistencia_delete' asistencia.id %}"
                                    class="btn btn-danger btn-circle btn-sm">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <h1 class="mt-4">Registro De Asistencia</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{% url 'nomina:inicio' %}">SEUNICSA</a></li>
            <li class="breadcrumb-item active">Asistencia</li>
        </ol>
        <div class="card mb-4">
            <div class="card-body">
                Agregar un nuevo registro al sistema de nomina <strong>SEUNICSA</strong>
                <div class=" py-3">
                    <a href="{% url 'nomina:asistencia_create' %}" class="btn btn-primary"><i
                            class="fas fa-plus-circle"></i> Agregar</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}